# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Createddate'),
        ),
    ]
