# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20151216_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlname',
            field=models.CharField(default='', max_length=61, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='urlname',
            field=models.CharField(default='', max_length=61, unique=True),
        ),
    ]
