# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20151216_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='forums.Forum'),
            preserve_default=False,
        ),
    ]
