# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20151217_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='commenttext',
        ),
    ]
